# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # pull_request_target
  pull_request_target:
    types: [opened, edited, reopened, synchronize, labeled]
    paths:
    - 'Code/code2/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false 
          fetch-depth: 0
      - name: Run script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            & ".script/script.ps1"
          azPSVersion: "latest"
          errorActionPreference: continue
          failOnStandardError: false
